#!/bin/sh

XCDANGER_TEST_PROJECT="`pwd`/test/Test Project/Test Project.xcodeproj"
echo "XCDANGER_TEST_PROJECT: ${XCDANGER_TEST_PROJECT}"

XCDANGER_TEST_PROJECT_MODEL="${XCDANGER_TEST_PROJECT}/project.pbxproj"
XCDANGER_TEMP="${XCDANGER_TEST_PROJECT}.tmp"

sed 's/SDKROOT = iphoneos;/SDKROOT = macosx10.12;/g' "${XCDANGER_TEST_PROJECT_MODEL}" > "${XCDANGER_TEMP}"

rm "${XCDANGER_TEST_PROJECT_MODEL}"
mv "${XCDANGER_TEMP}" "${XCDANGER_TEST_PROJECT_MODEL}"

sh output-build-settings.sh "${XCDANGER_TEST_PROJECT}"
